import { Container } from "@mui/material";
import Image from "next/image";
import bird from "../../public/images/black-kite-milvus-migrans-sky.jpg";
import drone from "../../public/images/drone.svg";
import hour from "../../public/images/zone.svg";
import hour2 from "../../public/images/Group 2322.svg";
import flag from "../../public/images/flags.svg";
import hired from "../../public/images/pilot search.svg";
import gear from "../../public/images/airpass verification.svg";

import Accordion from "@mui/material/Accordion";
import AccordionSummary from "@mui/material/AccordionSummary";
import AccordionDetails from "@mui/material/AccordionDetails";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

import Link from "next/link";
import Head from "next/head";
import Faq from "../../components/shared/Faq";

const Haitham = () => {
  return (
    <>
      <Head>
        <title>Tahleeq | Haitham</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/purple logo.svg" />
      </Head>

      <div className="haitham">
        <Container fixed>
          <div className="plan">
            <h2>AL HAITHAM Plan</h2>

            <p>
              This is the ultimate package where you can be a commercial drone
              operator
            </p>
          </div>
        </Container>

        <Image className="birdImage" src={bird} alt="bird" height={900} />

        <Container fixed>
          <div className="whatIn">
            <h3>What’s In AL HAITHAM?</h3>

            <div className="cards">
              <div className="card">
                <div className="box">
                  <Image
                    className="icon"
                    src={drone}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p>
                  1 <sup>St</sup> Drone
                </p>
                <p>Free</p>
                <p>Registration</p>
              </div>

              <div className="card">
                <div className="box">
                  <Image
                    className="icon"
                    src={hour}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p>Unlimited </p>
                <p>Flights Per </p>
                <p>Month</p>
              </div>

              <div className="card">
                <div className="box">
                  <Image
                    className="icon"
                    src={flag}
                    alt="new"
                    height={65}
                    width={65}
                  />
                </div>

                <p>All Types </p>
                <p>Of Missions </p>
              </div>

              <div className="card hiringCard">
                <div className="box">
                  <Image
                    className="icon"
                    src={hired}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p className="hired">Can Be Hired </p>
              </div>

              <div className="card gearCard">
                <div className="box">
                  <Image
                    className="icon"
                    src={gear}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p>CERTIFICATE </p>
                <p>Gained Through </p>
                <p>Accredited </p>
                <p>Institute </p>
              </div>

              <div className="card exclusiveCard">
                <div className="box">
                  <Image
                    className="icon"
                    src={hour2}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p>Exclusive </p>
                <p> Zones </p>
              </div>
            </div>
          </div>
          <div className="details">
            <Accordion className="accordion">
              <AccordionSummary
                expandIcon={<ExpandMoreIcon className="icon" />}
                aria-controls="panel1a-content"
                id="panel1a-header"
              >
                <h3>Details</h3>
              </AccordionSummary>
              <AccordionDetails className="wrap-box">
                <ul>
                  <li>
                    <p>Free registration for one drone only.</p>
                  </li>

                  <li>
                    <p>Ultimate flight hours per month are included. </p>
                  </li>

                  <li>
                    <p>All types of missions are included.</p>
                  </li>

                  <li>
                    <p>Flying in a safe zone is included.</p>
                  </li>

                  <li>
                    <p>
                      pilots will have hiring opportunities is certificate is
                      gained only .
                    </p>
                  </li>

                  <li>
                    <p>
                      You can upgrade your plan with a certificate to be a
                      commercial pilot <Link href={"./"}> learn more</Link>.
                    </p>
                  </li>

                  <li>
                    <p>The subscription is valid for one month only. </p>
                  </li>

                  <li>
                    <p>
                      Extra flying time can be added as{" "}
                      <Link href={"./"}> Add-Ons</Link> .
                    </p>
                  </li>

                  <li>
                    <p className="soon">
                      Exclusive zones to fly in (this feature will be added
                      soon).
                    </p>
                  </li>

                  <li>
                    <p> Prices are inclusive of 5% VAT.</p>
                  </li>
                </ul>
              </AccordionDetails>
            </Accordion>
          </div>

          <div className="subscribe">
            <button className="570px:normal-case">SUBSCRIBE NOW</button>
          </div>

          <div className="upgrade">
            <Accordion className="accordion">
              <AccordionSummary
                expandIcon={<ExpandMoreIcon className="icon" />}
                aria-controls="panel1a-content"
                id="panel1a-header"
              >
                <h3>Upgrade To Commercial Pilot</h3>
              </AccordionSummary>
              <AccordionDetails className="wrap-box">
                <ul>
                  <li>
                    <p>
                      The hiring missions included are photography and drone
                      racing, but they can be upgraded to all missions upon
                      getting a training certificate.
                    </p>
                  </li>

                  <li>
                    <p>
                      A training certificate can be obtained for an additional
                      fee of 350 OMR under the supervision of an accredited
                      institute.
                    </p>
                  </li>

                  <li>
                    <p>
                      Access to the training certificate can be found in{" "}
                      <Link href={"./"}> Add-Ons</Link> .
                    </p>
                  </li>

                  <li>
                    <p>
                      Pilots who have successfully obtained their certificate
                      will automatically upgrade to commercial operators and
                      start their journey.
                    </p>
                  </li>
                </ul>

                <div className="commercial">
                  <p>Get Your Certificate To Be Commercial Drone Pilot</p>

                  <button>Upgrade To Commercial Pilot </button>
                </div>
              </AccordionDetails>
            </Accordion>
          </div>
          <div className="faq">
            <Accordion className="accordion">
              <AccordionSummary
                expandIcon={<ExpandMoreIcon className="icon" />}
                aria-controls="panel1a-content"
                id="panel1a-header"
              >
                <h3>FAQs</h3>
              </AccordionSummary>
              <AccordionDetails className="wrap-box">
                <div className="box">
                  <p className="question">
                    Can I Be Hired With Al Haitham’s Plan?
                  </p>

                  <p className="answer">
                    Yes, You Can Be Hired For All Types Of Missions If You Have
                    A Certificate Only.
                  </p>
                </div>

                <div className="box">
                  <p className="question">How long is each flight?</p>

                  <p className="answer">
                    You can fly your drone for 30 minutes per flight.
                  </p>
                </div>

                <div className="box">
                  <p className="question">Do I have flight limits?</p>

                  <p className="answer">
                    No, Your Flights Are Unlimited. But There Is An Expiration
                    Date For The Flight’s Package Of One Month.
                  </p>
                </div>

                <div className="box">
                  <p className="question">How Long Is Al Haitham’s Plan?</p>

                  <p className="answer">
                    Al Haitham’s Plan Is Active For One Month.
                  </p>
                </div>

                <div className="box">
                  <p className="question">
                    How can I add extra flights after one month?
                  </p>

                  <p className="answer">
                    You need to subscribe again to one of the plans, and you
                    will get flying hours with the plan, If you have consumed
                    all your flying hours, you can purchase extra flying hours
                    from <Link href={"/add-ons"}>Add-Ons</Link> .
                  </p>
                </div>

                <div className="box">
                  <p className="question">Where can I fly my drone?</p>

                  <p className="answer">
                    You can fly in all the safe zones shown on the map.
                  </p>
                </div>
              </AccordionDetails>
            </Accordion>
          </div>
        </Container>
      </div>
    </>
  );
};

export default Haitham;
