import { Container } from "@mui/material";
import Head from "next/head";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import AddCircleIcon from "@mui/icons-material/AddCircle";
import Image from "next/image";
import Faq from "../../components/shared/Faq";

const Index = () => {
  return (
    <>
      <Head>
        <title>Tahleeq | New-Plan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/purple logo.svg" />
      </Head>

      <div className="osfur">
        <Container fixed>
          <div className="plan">
            <h2 className="text-orange-600">SERB Plans</h2>
            <p>
              SERB plans gives you drones, flights and more. Subscribe to your
              favourite plan and enjoy the best offers
            </p>
          </div>
        </Container>

        <Container fixed className="border-t-2 border-b-2">
          <div className="py-10">
            <h1 className="text-2xl font-bold mb-6">Choose Your Plan</h1>
            <div className="grid grid-cols-9 1200px:grid-cols-7 900px:grid-cols-4 570px:grid-cols-2 gap-4">
              <div className="cursor-pointer hover:bg-orange-600 hover:text-white group col-span-2 border border-orange-600 rounded-xl max-w-[250px] mx-auto">
                <div className="py-2 border-b-orange-300 border-b">
                  <div className="text-center">
                    <h2 className="font-semibold text-2xl text-orange-600 group-hover:text-white uppercase">
                      Osfour
                    </h2>
                    <h4 className="text-sm">Fly For Fun</h4>
                  </div>
                </div>
                <div className="text-center p-3">
                  <h2 className="text-orange-600 group-hover:text-white text-4xl font-extrabold">
                    10
                  </h2>
                  <h2 className="text-orange-600 group-hover:text-white text-sm -mt-1">
                    Flight Hours
                  </h2>
                  <h4 className="text-zinc-500 group-hover:text-white text-sm my-1">
                    Safe Zones
                  </h4>
                  <p className="my-2 text-zinc-500 group-hover:text-white">
                    1st Drone Free Registeration
                  </p>
                  <div className="bg-orange-600 group-hover:bg-white p-2 rounded-xl text-white group-hover:text-orange-600 flex items-center justify-between">
                    <div className="flex">
                      <span className="uppercase">Omr</span>
                      <div className="flex mx-3">
                        <span className="text-4xl">9</span>
                        <span className="self-end text-sm"> / Months</span>
                      </div>
                    </div>
                    <ChevronRightIcon fontSize="medium" />
                  </div>
                </div>
              </div>

              <div className="cursor-pointer col-span-2 border border-blue-600 hover:bg-blue-600 group rounded-xl relative max-w-[250px] mx-auto">
                <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-full py-0.5 px-3.5 rounded-t-md text-sm bg-rose-500 text-white">
                  Popular
                </div>
                <div className="py-2 border-b-blue-300 border-b">
                  <div className="text-center">
                    <h2 className="font-semibold text-2xl text-blue-600 group-hover:text-white uppercase">
                      Nawras
                    </h2>
                    <h4 className="text-sm group-hover:text-white">
                      Photographers Favourites
                    </h4>
                  </div>
                </div>
                <div className="text-center p-3">
                  <h2 className="text-blue-600 text-4xl font-extrabold group-hover:text-white">
                    20
                  </h2>
                  <h2 className="text-blue-600 text-sm -mt-1 group-hover:text-white">
                    Flight Hours
                  </h2>
                  <h4 className="text-zinc-500 text-sm my-1 group-hover:text-white">
                    Safe Zones
                  </h4>
                  <p className="my-2 text-zinc-500 group-hover:text-white">
                    1st Drone Free Registeration
                  </p>
                  <div className="bg-blue-600 group-hover:bg-white p-2 rounded-xl text-white group-hover:text-blue-600 flex items-center justify-between">
                    <div className="flex">
                      <span className="uppercase">Omr</span>
                      <div className="flex mx-3">
                        <span className="text-4xl">17</span>
                        <span className="self-end text-sm"> / Months</span>
                      </div>
                    </div>
                    <ChevronRightIcon fontSize="medium" />
                  </div>
                </div>
              </div>

              <div className="cursor-pointer col-span-2 border border-black hover:bg-black group hover:text-white rounded-xl max-w-[250px] mx-auto">
                <div className="py-2 border-b-black border-b">
                  <div className="text-center">
                    <h2 className="font-semibold text-2xl text-black group-hover:text-white uppercase">
                      Alhaitham
                    </h2>
                    <h4 className="text-sm">Commercial Done Pilot</h4>
                  </div>
                </div>
                <div className="text-center p-3">
                  <h2 className="text-4xl font-extrabold uppercase">
                    UnLimited
                  </h2>
                  <h2 className="text-sm -mt-1">Flight Hours</h2>
                  <h4 className="text-zinc-500 group-hover:text-white text-sm my-1">
                    1st Drone Free Registeration
                  </h4>
                  <p className="my-2 text-zinc-500 group-hover:text-white">
                    Eligible To Upgrade To Commercial Pilot
                  </p>
                  <div className="bg-black group-hover:bg-white p-2 rounded-xl text-white group-hover:text-black flex items-center justify-between">
                    <div className="flex">
                      <span className="uppercase">Omr</span>
                      <div className="flex mx-3">
                        <span className="text-4xl">25</span>
                        <span className="self-end text-sm"> / Months</span>
                      </div>
                    </div>
                    <ChevronRightIcon fontSize="medium" />
                  </div>
                </div>
              </div>
            </div>
            <ul className="my-7 list-disc list-inside">
              <li>Prices Inclusive 5% VAT.</li>
              <li>All subscriptions can be upgraded.</li>
            </ul>
          </div>
        </Container>
        <Container fixed className="border-t-2 border-b-2">
          <div className="py-10">
            <h1 className="text-2xl font-bold mb-4">Add-Ons</h1>
            <div className="flex mb-10">
              <div className="-mt-4">
                <Image
                  src="/images/menu-drone.svg"
                  className="object-contain"
                  height={80}
                  width={80}
                  alt="Menu Drone Img!"
                />
              </div>
              <div className="mx-3">
                <h3 className="text-2xl">Flights</h3>
                <h5 className="text-2xl">Never Stop Flying</h5>
                <div className="m-7 400px:m-2 grid grid-cols-4 1200px:grid-cols-3 900px:grid-cols-2 570px:grid-cols-1 gap-4">
                  {[1, 2, 3, 4].map((i) => (
                    <div
                      key={i}
                      className="cursor-pointer group hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center"
                    >
                      <Image
                        src="/images/menu-drone.svg"
                        className="object-contain"
                        height={65}
                        width={70}
                        alt="Menu Drone Img!"
                      />
                      <h3 className="text-xl font-semibold">10 Hours</h3>
                      <h5 className="block group-hover:hidden">Per week</h5>
                      <h2 className="text-3xl font-semibold mt-1">5 OMR</h2>
                      <button className="items-center mt-2 hidden group-hover:flex">
                        <AddCircleIcon
                          fontSize="medium"
                          className="text-rose-500"
                        />
                        <span className="mx-2">Buy Now</span>
                      </button>
                    </div>
                  ))}
                  {/* <div className="cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/menu-drone.svg"
                      className="object-contain"
                      height={65}
                      width={70}
                      alt="Menu Drone Img!"
                    />
                    <h3 className="text-2xl font-semibold">30 Minutes</h3>
                    <h2 className="text-2xl font-semibold -mt-1">5 OMR</h2>
                    <button className="flex items-center mt-2">
                      <AddCircleIcon
                        fontSize="medium"
                        className="text-rose-500"
                      />
                      <span className="mx-2">Buy Now</span>
                    </button>
                  </div> */}
                  {/* <div className="cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/menu-drone.svg"
                      className="object-contain"
                      height={65}
                      width={70}
                      alt="Menu Drone Img!"
                    />
                    <h3 className="text-xl font-semibold">10 Hours</h3>
                    <h5>Per week</h5>
                    <h2 className="text-3xl font-semibold mt-1">5 OMR</h2>
                  </div>
                  <div className="cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/menu-drone.svg"
                      className="object-contain"
                      height={65}
                      width={70}
                      alt="Menu Drone Img!"
                    />
                    <h3 className="text-2xl font-semibold">30 Minutes</h3>
                    <h2 className="text-2xl font-semibold -mt-1">5 OMR</h2>
                    <button className="flex items-center mt-2">
                      <AddCircleIcon
                        fontSize="medium"
                        className="text-rose-500"
                      />
                      <span className="mx-2">Buy Now</span>
                    </button>
                  </div>
                  <div className="cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/menu-drone.svg"
                      className="object-contain"
                      height={65}
                      width={70}
                      alt="Menu Drone Img!"
                    />
                    <h3 className="text-xl font-semibold">1 Week</h3>
                    <h5>15 Flights</h5>
                    <h2 className="text-3xl font-semibold mt-1">10 OMR</h2>
                  </div>
                  <div className="cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/menu-drone.svg"
                      className="object-contain"
                      height={65}
                      width={70}
                      alt="Menu Drone Img!"
                    />
                    <h3 className="text-xl font-semibold">1 Month</h3>
                    <h5>20 Flights</h5>
                    <h2 className="text-3xl font-semibold mt-1">15 OMR</h2>
                  </div> */}
                </div>
              </div>
            </div>
            <div className="flex mb-10">
              <div className="-mt-4">
                <Image
                  src="/images/drone.svg"
                  className="object-contain"
                  height={50}
                  width={50}
                  alt="Menu Drone Img!"
                />
              </div>
              <div className="mx-5 -mt-3">
                <h3 className="text-2xl">Drones</h3>
                <h5 className="text-2xl">Add Extra Drone</h5>
                <div className="mx-10 my-7 400px:mx-7 400px:my-2 grid grid-cols-4 1200px:grid-cols-3 900px:grid-cols-2 570px:grid-cols-1 gap-4">
                  <div className="pt-4 cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/drone.svg"
                      className="object-contain"
                      height={35}
                      width={35}
                      alt="Drone Img!"
                    />
                    <h3 className="text-xl font-semibold pt-3">1 Drone</h3>
                    <h5>Annual Registeration</h5>
                    <h2 className="text-3xl font-semibold mt-1">35 OMR</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Container>
        <Container
          fixed
          className="new-plan-container"
          style={{ padding: "0" }}
        >
          <Faq />
        </Container>
      </div>
    </>
  );
};

export default Index;
