import { Container } from "@mui/material";
import Image from "next/image";
import bird from "../../public/images/low-angle-bird-sky.jpg";
import drone from "../../public/images/drone.svg";
import hour from "../../public/images/zone.svg";
import flag from "../../public/images/flags.svg";

import Accordion from "@mui/material/Accordion";
import AccordionSummary from "@mui/material/AccordionSummary";
import AccordionDetails from "@mui/material/AccordionDetails";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import Link from "next/link";
import Head from "next/head";

const Osfur = () => {
  return (
    <>
      <Head>
        <title>Tahleeq | Osfur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/purple logo.svg" />
      </Head>

      <div className="osfur">
        <Container fixed>
          <div className="plan">
            <h2>OSFUR Plan</h2>

            <p>This package is for pilots who wants to fly alone and for fun</p>
          </div>
        </Container>

        <Image className="birdImage" src={bird} alt="bird" height={500} />

        <Container fixed>
          <div className="whatIn">
            <h3>What’s In OSFUR?</h3>

            <div className="cards">
              <div className="card">
                <div className="box">
                  <Image
                    className="icon"
                    src={drone}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p>
                  1 <sup>St</sup> Drone
                </p>
                <p>Free</p>
                <p>Registration</p>
              </div>

              <div className="card">
                <div className="box">
                  <Image
                    className="icon"
                    src={hour}
                    alt="new"
                    height={50}
                    width={50}
                  />
                </div>

                <p>10 Hours </p>
                <p>Flights Per </p>
                <p>Month</p>
              </div>

              <div className="card">
                <div className="box">
                  <Image
                    className="icon"
                    src={flag}
                    alt="new"
                    height={65}
                    width={65}
                  />
                </div>

                <p>Photography &</p>
                <p>Drone Racing </p>
                <p>Missions</p>
              </div>
            </div>
          </div>
          <div className="details">
            <Accordion className="accordion">
              <AccordionSummary
                expandIcon={<ExpandMoreIcon className="icon" />}
                aria-controls="panel1a-content"
                id="panel1a-header"
              >
                <h3>Details</h3>
              </AccordionSummary>
              <AccordionDetails className="wrap-box">
                <ul>
                  <li>
                    <p>Free registration for one drone only.</p>
                  </li>

                  <li>
                    <p>A flight time of 10 hours per month is included. </p>
                  </li>

                  <li>
                    <p>Missions included: Photography and drone racing only.</p>
                  </li>

                  <li>
                    <p>Flying in a safe zone is included.</p>
                  </li>

                  <li>
                    <p>
                      Extra flying time can be added as{" "}
                      <Link href={"./"}> Add-Ons</Link> .
                    </p>
                  </li>

                  <li>
                    <p>You can upgrade your plan.</p>
                  </li>

                  <li>
                    <p>The subscription is valid for one month only. </p>
                  </li>

                  <li>
                    <p> Prices are inclusive of 5% VAT.</p>
                  </li>
                </ul>
              </AccordionDetails>
            </Accordion>
          </div>

          <div className="subscribe">
            <button>SUBSCRIBE NOW</button>
          </div>

          <div className="faq">
            <Accordion className="accordion">
              <AccordionSummary
                expandIcon={<ExpandMoreIcon className="icon" />}
                aria-controls="panel1a-content"
                id="panel1a-header"
              >
                <h3>FAQs</h3>
              </AccordionSummary>
              <AccordionDetails className="wrap-box">
                <div className="box">
                  <p className="question">Can I be hired with Osfur’s plan?</p>

                  <p className="answer">
                    No, you need to upgrade to Al Haitham with a certificate.
                  </p>
                </div>

                <div className="box">
                  <p className="question">How long is each flight?</p>

                  <p className="answer">
                    You can fly your drone for 30 minutes per flight.
                  </p>
                </div>

                <div className="box">
                  <p className="question">Do I have flight limits?</p>

                  <p className="answer">
                    Yes, you have up to 10 hours of flying time per month.
                  </p>
                </div>

                <div className="box">
                  <p className="question">For how long is Osfur’s plan?</p>

                  <p className="answer">
                    The Osfur plan is active for one month.
                  </p>
                </div>

                <div className="box">
                  <p className="question">
                    How can I add extra flights after one month?
                  </p>

                  <p className="answer">
                    You need to subscribe again to one of the plans, and you
                    will get flying hours with the plan, If you have consumed
                    all your flying hours, you can purchase extra flying hours
                    from <Link href={"/add-ons"}>Add-Ons</Link> .
                  </p>
                </div>

                <div className="box">
                  <p className="question">Where can I fly my drone?</p>

                  <p className="answer">
                    You can fly in all the safe zones shown on the map.
                  </p>
                </div>
              </AccordionDetails>
            </Accordion>
          </div>
        </Container>
      </div>
    </>
  );
};

export default Osfur;
