import { Container } from "@mui/material";
import Head from "next/head";
import AddCircleIcon from "@mui/icons-material/AddCircle";
import Image from "next/image";
import Faq from "../../components/shared/Faq";

const Index = () => {
  return (
    <>
      <Head>
        <title>Tahleeq | Add-On</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/purple logo.svg" />
      </Head>

      <div className="osfur">
        <Container fixed>
          <div className="plan">
            <h2 className="text-orange-600">SERB Add-ons</h2>
            <p>
              SERB add-ons give you drones, flights and more. Add your favorite
              add-on and enjoy the best offers
            </p>
          </div>
        </Container>

        <Container fixed className="border-t-2 border-b-2">
          <div className="py-10">
            <h1 className="text-2xl font-bold mb-4">Add-Ons</h1>
            <div className="flex mb-10">
              <div className="-mt-4">
                <Image
                  src="/images/menu-drone.svg"
                  className="object-contain"
                  height={80}
                  width={80}
                  alt="Menu Drone Img!"
                />
              </div>
              <div className="mx-3">
                <h3 className="text-2xl">Flights</h3>
                <h5 className="text-2xl">Never Stop Flying</h5>
                <div className="m-7 400px:m-2 grid grid-cols-4 1200px:grid-cols-3 900px:grid-cols-2 570px:grid-cols-1 gap-4">
                  {[1, 2, 3, 4].map((i) => (
                    <div
                      key={i}
                      className="cursor-pointer group hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center"
                    >
                      <Image
                        src="/images/menu-drone.svg"
                        className="object-contain"
                        height={65}
                        width={70}
                        alt="Menu Drone Img!"
                      />
                      <h3 className="text-xl font-semibold">10 Hours</h3>
                      <h5 className="block group-hover:hidden">Per week</h5>
                      <h2 className="text-3xl font-semibold mt-1">5 OMR</h2>
                      <button className="items-center mt-2 hidden group-hover:flex">
                        <AddCircleIcon
                          fontSize="medium"
                          className="text-rose-500"
                        />
                        <span className="mx-2">Buy Now</span>
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="flex mb-10">
              <div className="-mt-4">
                <Image
                  src="/images/drone.svg"
                  className="object-contain"
                  height={50}
                  width={50}
                  alt="Menu Drone Img!"
                />
              </div>
              <div className="mx-5 -mt-3">
                <h3 className="text-2xl">Drones</h3>
                <h5 className="text-2xl">Add Extra Drone</h5>
                <div className="mx-10 my-7 400px:mx-7 400px:my-2 grid grid-cols-4 1200px:grid-cols-3 900px:grid-cols-2 570px:grid-cols-1 gap-4">
                  <div className="pt-4 cursor-pointer hover:bg-purple-800 hover:text-white transition-all duration-500 border border-purple-800 text-purple-800 rounded-md p-1 min-w-[200px] flex flex-col items-center justify-center">
                    <Image
                      src="/images/drone.svg"
                      className="object-contain"
                      height={35}
                      width={35}
                      alt="Drone Img!"
                    />
                    <h3 className="text-xl font-semibold pt-3">1 Drone</h3>
                    <h5>Annual Registeration</h5>
                    <h2 className="text-3xl font-semibold mt-1">35 OMR</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Container>
        <Container fixed style={{ padding: "0" }}>
          <Faq />
        </Container>
      </div>
    </>
  );
};

export default Index;
